Feature/bar chart
Finastra/finastra-design-system pull request #1054
Opened 2023-02-07 09:07 UTC by xmonvoisin

Bar chart feature

2023-02-07 09:54 UTC, xmonvoisin commented on libs/web-components/charts/src/apexcharts.ts
> +    categoricalPalette: ['#694ED6', '#F04E98', '#FFD100', '#ED8B00', '#7FCDDE', '#E5E5E5'],
![barchart](https://user-images.githubusercontent.com/5517756/217211698-f99033c4-7220-483a-b182-f98256786bd7.JPG)
It didn't fit the design I was given

2023-02-07 09:55 UTC, xmonvoisin commented on libs/web-components/charts/src/apexcharts.ts
> +    categoricalPalette: ['#694ED6', '#F04E98', '#FFD100', '#ED8B00', '#7FCDDE', '#E5E5E5'],
But maybe design is wrong I can revert

2023-02-07 15:13 UTC, rbordeanu requested changes

2023-02-07 15:13 UTC, rbordeanu commented on libs/web-components/charts/src/bar-chart-styles.scss
> +// :host([dense]) {
remove comments?

2023-02-07 15:13 UTC, rbordeanu commented on libs/web-components/charts/demo/index.html
> +    <div class="card">
formatting on this file should still be "2 spaces" right?

2023-02-08 09:31 UTC, dorsaffrigui commented on libs/web-components/charts/src/bar-chart.ts
> +
Nice work ! 
Could you add descriptions for the new attributes (xGrid, yGrid, stacked ... ) so that there are displayed in storybook  ?

2023-02-16 16:11 UTC, merged